### ISSUE TITLE
Send log using web

### ISSUE THREAD

**Issue by WathikAhmed** [FarmBot/farmbot-js#143]
Hi, this time im using the web file, Im looking to send a log to my farmbot. How is this done, the documentation is a bit confusing.

Thanks

**Comment by WathikAhmed** [comment]
With python its as simple as request_id1 = bot.send_message("Hello, this is being controlled through the API ")

**Comment by RickCarlino** [comment]
A few things:

1. I do agree that having synchronous return values like the example above is nice (common in languages like Ruby, Python, etc..) but this is not possible on the browser due to Javascript's I/O model. If anyone finds this issue via search, I recommend reading a [tutorial about Javascript promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises).
2. FarmBotJS does not have a `send_message` helper yet. No one has requested it until now. I can add this to a future version of FBJS, though. Thanks for letting us know.

**Comment by WathikAhmed** [comment]
Awesome, Thanks. Great Work!

**Comment by RickCarlino** [comment]
@WathikAhmed This feature is now available in v14.2.2:

```
bot.sendMessage("info", "Hello, world!");
```

**Comment by WathikAhmed** [comment]
Thank you very much @RickCarlino
